# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 559ad138eb248bec569d29ce6b5802e112c142782501949a017d113c5d1c30d7c472b78efe1efba43c47d0829dfd514b43ac4b328e9bd152114c247005054257

test:
  secret_key_base: 1846709c057d1612af667ce751e24c63ca0fef4317fad166117ae04ee160568eb056e5af03eeb849da6d8f5e936310821d91027e9e690f36cf66835c366f22fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
